[project]
name = "tasker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13.7"
dependencies = [
    "jsonschema>=4.25.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "ruff>=0.14.6",
]
